### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by OnlyloveSY** [Alan-FGR/SharpPhysX#3]
auto ret = *(new std::remove_pointer<PxGroupsMaskPtr>::type());
    auto heap = new char[sizeof PxGroupsMask];
There are many similar writing methods in the code, wouldn't this cause a memory leak?

**Comment by OnlyloveSY** [comment]
@Alan-FGR

**Comment by Alan-FGR** [comment]
Sorry for the late reply.
You're right. Not sure that's a bug in minBND or what.
If you need PhysX, I recommend this: https://github.com/MochiLibraries/Mochi.PhysX
I might at some point come back to this project, but no ETA and not too happy with the direction PhysX is going. PhysX 4 is still a pretty good physics engine though.
